### ISSUE TITLE
downloading error with foo's client

### ISSUE THREAD

**Issue by MrRoomba69** [Weathercold/extra-logging#1]
i get this when i try to download it
![Screenshot 2023-03-02 130558](https://user-images.githubusercontent.com/118114584/222513938-a1a66211-d0ff-4b43-b188-40ced1479c3c.png)

i think foo's client is the cause

**Comment by Weathercold** [comment]
java version? os? the error message?

**Comment by MrRoomba69** [comment]
os is windows

**Comment by Weathercold** [comment]
Can you reproduce this error with latest mod and Mindustry versions?

**Comment by MrRoomba69** [comment]
it worked on latest game and mod version
