### ISSUE TITLE
java.sql.Timestamp error on 143.1

### ISSUE THREAD

**Issue by cprince** [Weathercold/extra-logging#2]
Hi weathercold!

I get this when I try to install your mod today:
An error has occurred
(java.sql.Timestamp)
Thanks!

My system is MacOS 12.6.5
Mindustry 143.1
I have openjdk 11.0.9.1 2020-11-04 installed
<img width="609" alt="Screen Shot 2023-04-30 at 8 39 58 PM" src="https://user-images.githubusercontent.com/202651/235384219-5b382e47-2e34-4dbd-8208-6e88dc3d9cd4.png">
<img width="609" alt="Screen Shot 2023-04-30 at 8 40 11 PM" src="https://user-images.githubusercontent.com/202651/235384230-79038809-7088-45ba-be71-e9d669633625.png">
<img width="605" alt="Screen Shot 2023-04-30 at 8 40 22 PM" src="https://user-images.githubusercontent.com/202651/235384233-dc150d1b-06f2-4940-92de-f320fe47a113.png">

**Comment by Weathercold** [comment]
I think [this should be the issue](https://github.com/brandonbloom/fipp/issues/72#issuecomment-754745905). It seems that java.sql.* is not always on the classpath when using JDK9+. Can you confirm this by trying JDK8?

**Comment by cprince** [comment]
hrm, I'm not exactly familiar with classpath.

I installed openjdk8, but I get the same error

% java -version
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-bre_2023_04_25_03_23-b00)
OpenJDK 64-Bit Server VM (build 25.372-b00, mixed mode)

The Issue you link talks about a bootclasspath, how is that set?
